@localhost=localhost:4004/odata/v4/main
@id=4d5ae66d-f718-4e60-b390-85d0f5831731
@customerId=25734040-9a21-4ebc-9562-f37a4d3aa86c
@productId1=15842123-4557-4a3e-997d-c4e026813fd3
@productId2=22271538-8913-4c33-ad60-0d9e18723231

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 398,
    "items": [
        {
            "id": "0124aa1f-aa4e-44d0-b0ac-25cfdb6bd967",
            "header_id":"{{id}}",
            "product_id":"{{productId2}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "77823c1f-1ae1-466d-8292-59da92bf301f",
            "header_id":"{{id}}",
            "product_id":"{{productId2}}",
            "quantity": 5,
            "price": 1.99
        }
        
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{}

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{}